### PR TITLE
Fix Assign/unassign label from strings paths

### PR DESCRIPTION
**Pull request by xabk**
Fixed paths in labels.assign/unassign label from strings methods to include the "/strings" suffix

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @xabk, thanks a lot for your contribution! 🎉

**Comment by andrii-bodnar** [comment]
@xabk, some Unit tests failed, please check this - https://github.com/crowdin/crowdin-api-client-python/pull/25/checks

**Comment by xabk** [comment]
Hey @andrii-bodnar, I believe I've updated the tests to check for the fixed path now.

**Comment by andrii-bodnar** [comment]
@xabk great, thank you!

**Review by andrii-bodnar — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@xabk, the new version is available - [1.1.2](https://github.com/crowdin/crowdin-api-client-python/releases/tag/v1.1.2)

**Pull request merged**
