### PR TITLE
Move config parameters from class to instance #20

### PR DESCRIPTION
**Pull request by svenXY**
Implements a possible solution for #20

### CODE REVIEW

**Comment by svenXY** [comment]
OK, this does not work. It seems that constants changed in the subclass are somehow lost

**Comment by svenXY** [comment]
OK, I'm a little bit further, but some tests fail with `fixture 'requests_mock' not found` although I have requests-mock installed. I have some python knowledge, but pytest is not a daily for me

I'm running `pytest -vv`. Any ideas?

**Comment by andrii-bodnar** [comment]
@svenXY something wrong, the checks have failed again

**Comment by svenXY** [comment]
ah, yes: https://docs.python.org/3.10/whatsnew/3.10.html#pep-604-new-type-union-operator - i have `str|None` which is only supported since 3.10.

**Comment by svenXY** [comment]
Should work now. But honestly, maybe it is really better to drop the old approach with class constants as that would also mean that we could drop most of the `Optional[]s` in `__init__()`

**Comment by svenXY** [comment]
this last failure is something else and has afaiu nothing to do with my code:

'{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}'

**Comment by andrii-bodnar** [comment]
@svenXY Thank you!

Yes, it's something not related to your changes. Will try to investigate that

**Review by andrii-bodnar — APPROVED** [review]

**Pull request merged**
